apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
name: kargo

featureGates:
  # any feature gate can be enabled here with "Name": true
  # or disabled here with "Name": false
  # not all feature gates are tested, however
  "CSIMigration": true

runtimeConfig:
  "api/alpha": "false"

networking:
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
# apiServerAddress: "10.0.0.253"
# apiServerPort: 6443

nodes:
- role: control-plane
  # port forward 80 on the host to 80 on this node
  extraPortMappings:
  - hostPort: 80
    containerPort: 80
#   listenAddress: "10.0.0.253"
#   protocol: TCP
# extraPortMappings:
# - hostPort: 80
#   containerPort: 80
#   listenAddress: "0.0.0.0"
#   protocol: tcp
# - hostPort: 443
#   containerPort: 443
#   listenAddress: "0.0.0.0"
#   protocol: tcp
# - hostPort: 8080
#   containerPort: 8080
#   listenAddress: "0.0.0.0"
#   protocol: tcp
# - hostPort: 5000
#   containerPort: 5000
#   listenAddress: "0.0.0.0"
#   protocol: tcp
# - hostPort: 2222
#   containerPort: 2222
#   listenAddress: "0.0.0.0"
#   protocol: tcp
# - hostPort: 9097
#   containerPort: 9097
#   listenAddress: "0.0.0.0"
#   protocol: tcp
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
#---
#apiVersion: kubeadm.k8s.io/v1beta2
#kind: ClusterConfiguration
#kubernetesVersion: v1.16.0
#apiServer:
#  extraArgs:
#    anonymous-auth: "true"
#    audit-log-path: /tmp/kargo.log
#    enable-admission-plugins: AlwaysPullImages,DefaultStorageClass
#   advertise-address: "10.0.0.253:6443"

###########################################################################################
# https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/control-plane-flags
